/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from 'react';
import {StyleSheet, Text, View, Button} from 'react-native';
import {open} from 'react-native-open-developer-menu';

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>☆OpenDeveloperMenu example☆</Text>
      <Button onPress={open}>Open Developer Menu</Button>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});
